from pydantic import BaseModel, Field
from typing import List, Optional

class AnalyticsMetrics(BaseModel):
    """Structured metrics extracted from market research."""
    average_price: float = Field(description="The calculated average market price from research data")
    top_competitor: str = Field(description="The name of the primary market competitor identified")
    key_selling_points: List[str] = Field(description="List of top features driving sales for this product")
    customer_sentiment: str = Field(description="A concise summary of customer pros and cons")

class AgentAnalysisOutput(BaseModel):
    """The complete structured contract for the analysis pipeline."""
    metrics: Optional[AnalyticsMetrics] = None
    growth_strategy: Optional[str] = Field(None, description="The 3 strategies generated by the Optimization Agent")
    critic_review: Optional[str] = Field(None, description="The final validation note from the Critic Agent")
    confidence_score: float = Field(default=1.0, ge=0, le=1.0)