"""initial_schema

Revision ID: 16caa812c82b
Revises: 
Create Date: 2026-02-25 22:22:05.191016

"""
from typing import Sequence, Union
import pgvector
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16caa812c82b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('total_cost', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('node_latency', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('product_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1536),
               existing_nullable=True)
    op.drop_column('jobs', 'node_latency')
    op.drop_column('jobs', 'total_cost')
    op.drop_column('jobs', 'total_tokens')
    # ### end Alembic commands ###
