"""add_job_metadata_columns

Revision ID: 781002c89622
Revises: 66ed609e4af4
Create Date: 2026-03-14 11:32:18.203763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781002c89622'
down_revision: Union[str, Sequence[str], None] = '66ed609e4af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('execution_timeline', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('confidence_metrics', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('cost_metrics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'cost_metrics')
    op.drop_column('jobs', 'confidence_metrics')
    op.drop_column('jobs', 'execution_timeline')
    # ### end Alembic commands ###
